<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jh_pwcomments_feed"
 *
 * Auto generated by Extension Builder 2014-01-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'pw_comments feed',
	'description' => 'RSS- and Atom-Feed for EXT:pw_comments',
	'category' => 'plugin',
	'author' => 'Jonathan Heilmann',
	'author_email' => 'mail@jonathan-heilmann.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5.0-6.1.99',
			'pw_comments' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>